/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AhsapDogramaKapiModelleriRouteImport } from './routes/ahsap-dograma-kapi-modelleri'
import { Route as AmerikanPanelKapiModelleriRouteImport } from './routes/amerikan-panel-kapi-modelleri'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KurumsalRouteImport } from './routes/kurumsal'
import { Route as LakeKapiModelleriRouteImport } from './routes/lake-kapi-modelleri'
import { Route as MelaminKapiModelleriRouteImport } from './routes/melamin-kapi-modelleri'
import { Route as PvcKapiModelleriRouteImport } from './routes/pvc-kapi-modelleri'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AhsapDogramaKapiModelleriRoute =
  AhsapDogramaKapiModelleriRouteImport.update({
    id: '/ahsap-dograma-kapi-modelleri',
    path: '/ahsap-dograma-kapi-modelleri',
    getParentRoute: () => rootRouteImport,
  } as any)
const AmerikanPanelKapiModelleriRoute =
  AmerikanPanelKapiModelleriRouteImport.update({
    id: '/amerikan-panel-kapi-modelleri',
    path: '/amerikan-panel-kapi-modelleri',
    getParentRoute: () => rootRouteImport,
  } as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KurumsalRoute = KurumsalRouteImport.update({
  id: '/kurumsal',
  path: '/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const LakeKapiModelleriRoute = LakeKapiModelleriRouteImport.update({
  id: '/lake-kapi-modelleri',
  path: '/lake-kapi-modelleri',
  getParentRoute: () => rootRouteImport,
} as any)
const MelaminKapiModelleriRoute = MelaminKapiModelleriRouteImport.update({
  id: '/melamin-kapi-modelleri',
  path: '/melamin-kapi-modelleri',
  getParentRoute: () => rootRouteImport,
} as any)
const PvcKapiModelleriRoute = PvcKapiModelleriRouteImport.update({
  id: '/pvc-kapi-modelleri',
  path: '/pvc-kapi-modelleri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ahsap-dograma-kapi-modelleri': typeof AhsapDogramaKapiModelleriRoute
  '/amerikan-panel-kapi-modelleri': typeof AmerikanPanelKapiModelleriRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/lake-kapi-modelleri': typeof LakeKapiModelleriRoute
  '/melamin-kapi-modelleri': typeof MelaminKapiModelleriRoute
  '/pvc-kapi-modelleri': typeof PvcKapiModelleriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ahsap-dograma-kapi-modelleri': typeof AhsapDogramaKapiModelleriRoute
  '/amerikan-panel-kapi-modelleri': typeof AmerikanPanelKapiModelleriRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/lake-kapi-modelleri': typeof LakeKapiModelleriRoute
  '/melamin-kapi-modelleri': typeof MelaminKapiModelleriRoute
  '/pvc-kapi-modelleri': typeof PvcKapiModelleriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ahsap-dograma-kapi-modelleri': typeof AhsapDogramaKapiModelleriRoute
  '/amerikan-panel-kapi-modelleri': typeof AmerikanPanelKapiModelleriRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/lake-kapi-modelleri': typeof LakeKapiModelleriRoute
  '/melamin-kapi-modelleri': typeof MelaminKapiModelleriRoute
  '/pvc-kapi-modelleri': typeof PvcKapiModelleriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ahsap-dograma-kapi-modelleri'
    | '/amerikan-panel-kapi-modelleri'
    | '/iletisim'
    | '/kurumsal'
    | '/lake-kapi-modelleri'
    | '/melamin-kapi-modelleri'
    | '/pvc-kapi-modelleri'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ahsap-dograma-kapi-modelleri'
    | '/amerikan-panel-kapi-modelleri'
    | '/iletisim'
    | '/kurumsal'
    | '/lake-kapi-modelleri'
    | '/melamin-kapi-modelleri'
    | '/pvc-kapi-modelleri'
  id:
    | '__root__'
    | '/'
    | '/ahsap-dograma-kapi-modelleri'
    | '/amerikan-panel-kapi-modelleri'
    | '/iletisim'
    | '/kurumsal'
    | '/lake-kapi-modelleri'
    | '/melamin-kapi-modelleri'
    | '/pvc-kapi-modelleri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhsapDogramaKapiModelleriRoute: typeof AhsapDogramaKapiModelleriRoute
  AmerikanPanelKapiModelleriRoute: typeof AmerikanPanelKapiModelleriRoute
  IletisimRoute: typeof IletisimRoute
  KurumsalRoute: typeof KurumsalRoute
  LakeKapiModelleriRoute: typeof LakeKapiModelleriRoute
  MelaminKapiModelleriRoute: typeof MelaminKapiModelleriRoute
  PvcKapiModelleriRoute: typeof PvcKapiModelleriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ahsap-dograma-kapi-modelleri': {
      id: '/ahsap-dograma-kapi-modelleri'
      path: '/ahsap-dograma-kapi-modelleri'
      fullPath: '/ahsap-dograma-kapi-modelleri'
      preLoaderRoute: typeof AhsapDogramaKapiModelleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amerikan-panel-kapi-modelleri': {
      id: '/amerikan-panel-kapi-modelleri'
      path: '/amerikan-panel-kapi-modelleri'
      fullPath: '/amerikan-panel-kapi-modelleri'
      preLoaderRoute: typeof AmerikanPanelKapiModelleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurumsal': {
      id: '/kurumsal'
      path: '/kurumsal'
      fullPath: '/kurumsal'
      preLoaderRoute: typeof KurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lake-kapi-modelleri': {
      id: '/lake-kapi-modelleri'
      path: '/lake-kapi-modelleri'
      fullPath: '/lake-kapi-modelleri'
      preLoaderRoute: typeof LakeKapiModelleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melamin-kapi-modelleri': {
      id: '/melamin-kapi-modelleri'
      path: '/melamin-kapi-modelleri'
      fullPath: '/melamin-kapi-modelleri'
      preLoaderRoute: typeof MelaminKapiModelleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvc-kapi-modelleri': {
      id: '/pvc-kapi-modelleri'
      path: '/pvc-kapi-modelleri'
      fullPath: '/pvc-kapi-modelleri'
      preLoaderRoute: typeof PvcKapiModelleriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhsapDogramaKapiModelleriRoute: AhsapDogramaKapiModelleriRoute,
  AmerikanPanelKapiModelleriRoute: AmerikanPanelKapiModelleriRoute,
  IletisimRoute: IletisimRoute,
  KurumsalRoute: KurumsalRoute,
  LakeKapiModelleriRoute: LakeKapiModelleriRoute,
  MelaminKapiModelleriRoute: MelaminKapiModelleriRoute,
  PvcKapiModelleriRoute: PvcKapiModelleriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
